# Generated by Django 4.1.6 on 2023-04-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceIncludingVAT',
            field=models.FloatField(default=0, verbose_name='Цена с учётом НДС'),
            preserve_default=False,
        ),
    ]
