# Generated by Django 4.1.6 on 2023-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0005_product_priceincludingvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='VAT',
            field=models.FloatField(default=1.1, verbose_name='НДС'),
            preserve_default=False,
        ),
    ]
