# Generated by Django 4.1.6 on 2023-04-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0007_remove_product_priceincludingvat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='VAT',
        ),
    ]
