# Generated by Django 4.1.6 on 2023-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0010_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
